const resultados = [
  {
    "nombre": "Juan",
    "imagen": "https://randomuser.me/api/portraits/men/1.jpg",
    "genero": "Hombre",
    "edad": 22,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3001234567"
  },
  {
    "nombre": "Ana",
    "imagen": "https://randomuser.me/api/portraits/women/2.jpg",
    "genero": "Mujer",
    "edad": 24,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3012345678"
  },
  {
    "nombre": "Carlos",
    "imagen": "https://randomuser.me/api/portraits/men/3.jpg",
    "genero": "Hombre",
    "edad": 23,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3023456789"
  },
  {
    "nombre": "Maria",
    "imagen": "https://randomuser.me/api/portraits/women/4.jpg",
    "genero": "Mujer",
    "edad": 21,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3034567890"
  },
  {
    "nombre": "Pedro",
    "imagen": "https://randomuser.me/api/portraits/men/5.jpg",
    "genero": "Hombre",
    "edad": 20,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3045678901"
  },
  {
    "nombre": "Sofia",
    "imagen": "https://randomuser.me/api/portraits/women/6.jpg",
    "genero": "Mujer",
    "edad": 19,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3056789012"
  },
  {
    "nombre": "Diego",
    "imagen": "https://randomuser.me/api/portraits/men/7.jpg",
    "genero": "Hombre",
    "edad": 18,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3067890123"
  },
  {
    "nombre": "Laura",
    "imagen": "https://randomuser.me/api/portraits/women/8.jpg",
    "genero": "Mujer",
    "edad": 23,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3078901234"
  },
  {
    "nombre": "Juan",
    "imagen": "https://randomuser.me/api/portraits/men/1.jpg",
    "genero": "Hombre",
    "edad": 22,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3001234567"
  },
  {
    "nombre": "Ana",
    "imagen": "https://randomuser.me/api/portraits/women/2.jpg",
    "genero": "Mujer",
    "edad": 24,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3012345678"
  },
  {
    "nombre": "Carlos",
    "imagen": "https://randomuser.me/api/portraits/men/3.jpg",
    "genero": "Hombre",
    "edad": 23,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3023456789"
  },
  {
    "nombre": "Maria",
    "imagen": "https://randomuser.me/api/portraits/women/4.jpg",
    "genero": "Mujer",
    "edad": 21,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3034567890"
  },
  {
    "nombre": "Pedro",
    "imagen": "https://randomuser.me/api/portraits/men/5.jpg",
    "genero": "Hombre",
    "edad": 20,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3045678901"
  },
  {
    "nombre": "Sofia",
    "imagen": "https://randomuser.me/api/portraits/women/6.jpg",
    "genero": "Mujer",
    "edad": 19,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3056789012"
  },
  {
    "nombre": "Diego",
    "imagen": "https://randomuser.me/api/portraits/men/7.jpg",
    "genero": "Hombre",
    "edad": 18,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3067890123"
  },
  {
    "nombre": "Laura",
    "imagen": "https://randomuser.me/api/portraits/women/8.jpg",
    "genero": "Mujer",
    "edad": 23,
    "ocupacion": "Estudiante",
    "mascotas": "Gato",
    "consumo": "Ninguno",
    "orden": "Ordenado",
    "ruido": "Silencioso",
    "interaccion": "Sociable",
    "invitados": "Sin restricciones",
    "telefono": "3078901234"
  }
]



export default resultados;
  